#!/bin/sh

### BEGIN INIT INFO
# Provides:          cpu-conservative
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Set the CPU in conservative mode
# Description:       Set the CPU in conservative mode
### END INIT INFO

# get ready to work
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

#CPU power management node
CPUMODE=conservative

#Update the default size in this file
. /etc/default/cpu-conservative

# what we are
NAME=cpu-conservative

case "$1" in

  start)
    /bin/echo "Starting ${NAME} ..."
    # Change
    /usr/bin/cpufreq-set -g ${CPUMODE}
    /bin/echo "done."
    ;;


  stop|default-stop)
    /bin/echo -n "Stopping ${NAME} ..."
    /bin/echo ", done."
    ;;


  restart|reload|force-reload)
    /bin/echo "No daemon to (force-)re[start|load] in ${NAME}"
    ;;


 *)
    /bin/echo "Usage: $0 {start|stop}"

    exit 1
    ;;

esac

exit 0
